name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: DeterminateSystems/nix-installer-action@v21

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Run checks
        run: nix develop --command just check
